name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Correr pruebas
        run: pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build imagen Docker
        run: docker build -t mi-api .

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build y push imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops:${{ github.sha }}
          build-args: |
            NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY }}

  deploy-render:
    needs: publish
    runs-on: ubuntu-latest
  
    if: github.ref == 'refs/heads/main'
  
    steps:
      - name: Deploy a Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
